/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TunnelRouteImport } from './routes/tunnel'
import { Route as RedirectRouteImport } from './routes/redirect'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DeliveryRouteImport } from './routes/delivery'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as StoreRouteRouteImport } from './routes/store/route'
import { Route as ProductRouteRouteImport } from './routes/product/route'
import { Route as NewsRouteRouteImport } from './routes/news/route'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StoreIndexRouteImport } from './routes/store/index'
import { Route as NewsIndexRouteImport } from './routes/news/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as StoreCheckoutRouteImport } from './routes/store/checkout'
import { Route as StoreCategorySlugRouteImport } from './routes/store/$categorySlug'
import { Route as ProductProductIdRouteImport } from './routes/product/$productId'
import { Route as OrderOrderIdRouteImport } from './routes/order/$orderId'
import { Route as NewsNewsSlugRouteImport } from './routes/news/$newsSlug'
import { Route as DashboardOrdersRouteImport } from './routes/dashboard/orders'
import { Route as DashboardNewsRouteImport } from './routes/dashboard/news'
import { Route as DashboardMiscRouteImport } from './routes/dashboard/misc'
import { Route as DashboardCollectionsRouteImport } from './routes/dashboard/collections'
import { Route as DashboardCategoriesRouteImport } from './routes/dashboard/categories'
import { Route as DashboardBrandsRouteImport } from './routes/dashboard/brands'
import { Route as DashboardAttributesRouteImport } from './routes/dashboard/attributes'
import { Route as DashboardProductsNewRouteImport } from './routes/dashboard/products.new'
import { Route as ApiAuthSplatRouteImport } from './routes/api.auth.$'
import { Route as DashboardProductsProductIdEditRouteImport } from './routes/dashboard/products.$productId.edit'

const TunnelRoute = TunnelRouteImport.update({
  id: '/tunnel',
  path: '/tunnel',
  getParentRoute: () => rootRouteImport,
} as any)
const RedirectRoute = RedirectRouteImport.update({
  id: '/redirect',
  path: '/redirect',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveryRoute = DeliveryRouteImport.update({
  id: '/delivery',
  path: '/delivery',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreRouteRoute = StoreRouteRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductRouteRoute = ProductRouteRouteImport.update({
  id: '/product',
  path: '/product',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRouteRoute = NewsRouteRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreIndexRoute = StoreIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StoreRouteRoute,
} as any)
const NewsIndexRoute = NewsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => NewsRouteRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const StoreCheckoutRoute = StoreCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => StoreRouteRoute,
} as any)
const StoreCategorySlugRoute = StoreCategorySlugRouteImport.update({
  id: '/$categorySlug',
  path: '/$categorySlug',
  getParentRoute: () => StoreRouteRoute,
} as any)
const ProductProductIdRoute = ProductProductIdRouteImport.update({
  id: '/$productId',
  path: '/$productId',
  getParentRoute: () => ProductRouteRoute,
} as any)
const OrderOrderIdRoute = OrderOrderIdRouteImport.update({
  id: '/order/$orderId',
  path: '/order/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsNewsSlugRoute = NewsNewsSlugRouteImport.update({
  id: '/$newsSlug',
  path: '/$newsSlug',
  getParentRoute: () => NewsRouteRoute,
} as any)
const DashboardOrdersRoute = DashboardOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardNewsRoute = DashboardNewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardMiscRoute = DashboardMiscRouteImport.update({
  id: '/misc',
  path: '/misc',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardCollectionsRoute = DashboardCollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardCategoriesRoute = DashboardCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardBrandsRoute = DashboardBrandsRouteImport.update({
  id: '/brands',
  path: '/brands',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardAttributesRoute = DashboardAttributesRouteImport.update({
  id: '/attributes',
  path: '/attributes',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardProductsNewRoute = DashboardProductsNewRouteImport.update({
  id: '/products/new',
  path: '/products/new',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardProductsProductIdEditRoute =
  DashboardProductsProductIdEditRouteImport.update({
    id: '/products/$productId/edit',
    path: '/products/$productId/edit',
    getParentRoute: () => DashboardRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/news': typeof NewsRouteRouteWithChildren
  '/product': typeof ProductRouteRouteWithChildren
  '/store': typeof StoreRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/delivery': typeof DeliveryRoute
  '/login': typeof LoginRoute
  '/redirect': typeof RedirectRoute
  '/tunnel': typeof TunnelRoute
  '/dashboard/attributes': typeof DashboardAttributesRoute
  '/dashboard/brands': typeof DashboardBrandsRoute
  '/dashboard/categories': typeof DashboardCategoriesRoute
  '/dashboard/collections': typeof DashboardCollectionsRoute
  '/dashboard/misc': typeof DashboardMiscRoute
  '/dashboard/news': typeof DashboardNewsRoute
  '/dashboard/orders': typeof DashboardOrdersRoute
  '/news/$newsSlug': typeof NewsNewsSlugRoute
  '/order/$orderId': typeof OrderOrderIdRoute
  '/product/$productId': typeof ProductProductIdRoute
  '/store/$categorySlug': typeof StoreCategorySlugRoute
  '/store/checkout': typeof StoreCheckoutRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/news/': typeof NewsIndexRoute
  '/store/': typeof StoreIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard/products/new': typeof DashboardProductsNewRoute
  '/dashboard/products/$productId/edit': typeof DashboardProductsProductIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/product': typeof ProductRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/delivery': typeof DeliveryRoute
  '/login': typeof LoginRoute
  '/redirect': typeof RedirectRoute
  '/tunnel': typeof TunnelRoute
  '/dashboard/attributes': typeof DashboardAttributesRoute
  '/dashboard/brands': typeof DashboardBrandsRoute
  '/dashboard/categories': typeof DashboardCategoriesRoute
  '/dashboard/collections': typeof DashboardCollectionsRoute
  '/dashboard/misc': typeof DashboardMiscRoute
  '/dashboard/news': typeof DashboardNewsRoute
  '/dashboard/orders': typeof DashboardOrdersRoute
  '/news/$newsSlug': typeof NewsNewsSlugRoute
  '/order/$orderId': typeof OrderOrderIdRoute
  '/product/$productId': typeof ProductProductIdRoute
  '/store/$categorySlug': typeof StoreCategorySlugRoute
  '/store/checkout': typeof StoreCheckoutRoute
  '/dashboard': typeof DashboardIndexRoute
  '/news': typeof NewsIndexRoute
  '/store': typeof StoreIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard/products/new': typeof DashboardProductsNewRoute
  '/dashboard/products/$productId/edit': typeof DashboardProductsProductIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/news': typeof NewsRouteRouteWithChildren
  '/product': typeof ProductRouteRouteWithChildren
  '/store': typeof StoreRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/delivery': typeof DeliveryRoute
  '/login': typeof LoginRoute
  '/redirect': typeof RedirectRoute
  '/tunnel': typeof TunnelRoute
  '/dashboard/attributes': typeof DashboardAttributesRoute
  '/dashboard/brands': typeof DashboardBrandsRoute
  '/dashboard/categories': typeof DashboardCategoriesRoute
  '/dashboard/collections': typeof DashboardCollectionsRoute
  '/dashboard/misc': typeof DashboardMiscRoute
  '/dashboard/news': typeof DashboardNewsRoute
  '/dashboard/orders': typeof DashboardOrdersRoute
  '/news/$newsSlug': typeof NewsNewsSlugRoute
  '/order/$orderId': typeof OrderOrderIdRoute
  '/product/$productId': typeof ProductProductIdRoute
  '/store/$categorySlug': typeof StoreCategorySlugRoute
  '/store/checkout': typeof StoreCheckoutRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/news/': typeof NewsIndexRoute
  '/store/': typeof StoreIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard/products/new': typeof DashboardProductsNewRoute
  '/dashboard/products/$productId/edit': typeof DashboardProductsProductIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/news'
    | '/product'
    | '/store'
    | '/about'
    | '/contact'
    | '/delivery'
    | '/login'
    | '/redirect'
    | '/tunnel'
    | '/dashboard/attributes'
    | '/dashboard/brands'
    | '/dashboard/categories'
    | '/dashboard/collections'
    | '/dashboard/misc'
    | '/dashboard/news'
    | '/dashboard/orders'
    | '/news/$newsSlug'
    | '/order/$orderId'
    | '/product/$productId'
    | '/store/$categorySlug'
    | '/store/checkout'
    | '/dashboard/'
    | '/news/'
    | '/store/'
    | '/api/auth/$'
    | '/dashboard/products/new'
    | '/dashboard/products/$productId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/product'
    | '/about'
    | '/contact'
    | '/delivery'
    | '/login'
    | '/redirect'
    | '/tunnel'
    | '/dashboard/attributes'
    | '/dashboard/brands'
    | '/dashboard/categories'
    | '/dashboard/collections'
    | '/dashboard/misc'
    | '/dashboard/news'
    | '/dashboard/orders'
    | '/news/$newsSlug'
    | '/order/$orderId'
    | '/product/$productId'
    | '/store/$categorySlug'
    | '/store/checkout'
    | '/dashboard'
    | '/news'
    | '/store'
    | '/api/auth/$'
    | '/dashboard/products/new'
    | '/dashboard/products/$productId/edit'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/news'
    | '/product'
    | '/store'
    | '/about'
    | '/contact'
    | '/delivery'
    | '/login'
    | '/redirect'
    | '/tunnel'
    | '/dashboard/attributes'
    | '/dashboard/brands'
    | '/dashboard/categories'
    | '/dashboard/collections'
    | '/dashboard/misc'
    | '/dashboard/news'
    | '/dashboard/orders'
    | '/news/$newsSlug'
    | '/order/$orderId'
    | '/product/$productId'
    | '/store/$categorySlug'
    | '/store/checkout'
    | '/dashboard/'
    | '/news/'
    | '/store/'
    | '/api/auth/$'
    | '/dashboard/products/new'
    | '/dashboard/products/$productId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  NewsRouteRoute: typeof NewsRouteRouteWithChildren
  ProductRouteRoute: typeof ProductRouteRouteWithChildren
  StoreRouteRoute: typeof StoreRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  DeliveryRoute: typeof DeliveryRoute
  LoginRoute: typeof LoginRoute
  RedirectRoute: typeof RedirectRoute
  TunnelRoute: typeof TunnelRoute
  OrderOrderIdRoute: typeof OrderOrderIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tunnel': {
      id: '/tunnel'
      path: '/tunnel'
      fullPath: '/tunnel'
      preLoaderRoute: typeof TunnelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redirect': {
      id: '/redirect'
      path: '/redirect'
      fullPath: '/redirect'
      preLoaderRoute: typeof RedirectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delivery': {
      id: '/delivery'
      path: '/delivery'
      fullPath: '/delivery'
      preLoaderRoute: typeof DeliveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store': {
      id: '/store'
      path: '/store'
      fullPath: '/store'
      preLoaderRoute: typeof StoreRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product': {
      id: '/product'
      path: '/product'
      fullPath: '/product'
      preLoaderRoute: typeof ProductRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store/': {
      id: '/store/'
      path: '/'
      fullPath: '/store/'
      preLoaderRoute: typeof StoreIndexRouteImport
      parentRoute: typeof StoreRouteRoute
    }
    '/news/': {
      id: '/news/'
      path: '/'
      fullPath: '/news/'
      preLoaderRoute: typeof NewsIndexRouteImport
      parentRoute: typeof NewsRouteRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/store/checkout': {
      id: '/store/checkout'
      path: '/checkout'
      fullPath: '/store/checkout'
      preLoaderRoute: typeof StoreCheckoutRouteImport
      parentRoute: typeof StoreRouteRoute
    }
    '/store/$categorySlug': {
      id: '/store/$categorySlug'
      path: '/$categorySlug'
      fullPath: '/store/$categorySlug'
      preLoaderRoute: typeof StoreCategorySlugRouteImport
      parentRoute: typeof StoreRouteRoute
    }
    '/product/$productId': {
      id: '/product/$productId'
      path: '/$productId'
      fullPath: '/product/$productId'
      preLoaderRoute: typeof ProductProductIdRouteImport
      parentRoute: typeof ProductRouteRoute
    }
    '/order/$orderId': {
      id: '/order/$orderId'
      path: '/order/$orderId'
      fullPath: '/order/$orderId'
      preLoaderRoute: typeof OrderOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/$newsSlug': {
      id: '/news/$newsSlug'
      path: '/$newsSlug'
      fullPath: '/news/$newsSlug'
      preLoaderRoute: typeof NewsNewsSlugRouteImport
      parentRoute: typeof NewsRouteRoute
    }
    '/dashboard/orders': {
      id: '/dashboard/orders'
      path: '/orders'
      fullPath: '/dashboard/orders'
      preLoaderRoute: typeof DashboardOrdersRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/news': {
      id: '/dashboard/news'
      path: '/news'
      fullPath: '/dashboard/news'
      preLoaderRoute: typeof DashboardNewsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/misc': {
      id: '/dashboard/misc'
      path: '/misc'
      fullPath: '/dashboard/misc'
      preLoaderRoute: typeof DashboardMiscRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/collections': {
      id: '/dashboard/collections'
      path: '/collections'
      fullPath: '/dashboard/collections'
      preLoaderRoute: typeof DashboardCollectionsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/categories': {
      id: '/dashboard/categories'
      path: '/categories'
      fullPath: '/dashboard/categories'
      preLoaderRoute: typeof DashboardCategoriesRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/brands': {
      id: '/dashboard/brands'
      path: '/brands'
      fullPath: '/dashboard/brands'
      preLoaderRoute: typeof DashboardBrandsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/attributes': {
      id: '/dashboard/attributes'
      path: '/attributes'
      fullPath: '/dashboard/attributes'
      preLoaderRoute: typeof DashboardAttributesRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/products/new': {
      id: '/dashboard/products/new'
      path: '/products/new'
      fullPath: '/dashboard/products/new'
      preLoaderRoute: typeof DashboardProductsNewRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/products/$productId/edit': {
      id: '/dashboard/products/$productId/edit'
      path: '/products/$productId/edit'
      fullPath: '/dashboard/products/$productId/edit'
      preLoaderRoute: typeof DashboardProductsProductIdEditRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
  }
}

interface DashboardRouteRouteChildren {
  DashboardAttributesRoute: typeof DashboardAttributesRoute
  DashboardBrandsRoute: typeof DashboardBrandsRoute
  DashboardCategoriesRoute: typeof DashboardCategoriesRoute
  DashboardCollectionsRoute: typeof DashboardCollectionsRoute
  DashboardMiscRoute: typeof DashboardMiscRoute
  DashboardNewsRoute: typeof DashboardNewsRoute
  DashboardOrdersRoute: typeof DashboardOrdersRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardProductsNewRoute: typeof DashboardProductsNewRoute
  DashboardProductsProductIdEditRoute: typeof DashboardProductsProductIdEditRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardAttributesRoute: DashboardAttributesRoute,
  DashboardBrandsRoute: DashboardBrandsRoute,
  DashboardCategoriesRoute: DashboardCategoriesRoute,
  DashboardCollectionsRoute: DashboardCollectionsRoute,
  DashboardMiscRoute: DashboardMiscRoute,
  DashboardNewsRoute: DashboardNewsRoute,
  DashboardOrdersRoute: DashboardOrdersRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardProductsNewRoute: DashboardProductsNewRoute,
  DashboardProductsProductIdEditRoute: DashboardProductsProductIdEditRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

interface NewsRouteRouteChildren {
  NewsNewsSlugRoute: typeof NewsNewsSlugRoute
  NewsIndexRoute: typeof NewsIndexRoute
}

const NewsRouteRouteChildren: NewsRouteRouteChildren = {
  NewsNewsSlugRoute: NewsNewsSlugRoute,
  NewsIndexRoute: NewsIndexRoute,
}

const NewsRouteRouteWithChildren = NewsRouteRoute._addFileChildren(
  NewsRouteRouteChildren,
)

interface ProductRouteRouteChildren {
  ProductProductIdRoute: typeof ProductProductIdRoute
}

const ProductRouteRouteChildren: ProductRouteRouteChildren = {
  ProductProductIdRoute: ProductProductIdRoute,
}

const ProductRouteRouteWithChildren = ProductRouteRoute._addFileChildren(
  ProductRouteRouteChildren,
)

interface StoreRouteRouteChildren {
  StoreCategorySlugRoute: typeof StoreCategorySlugRoute
  StoreCheckoutRoute: typeof StoreCheckoutRoute
  StoreIndexRoute: typeof StoreIndexRoute
}

const StoreRouteRouteChildren: StoreRouteRouteChildren = {
  StoreCategorySlugRoute: StoreCategorySlugRoute,
  StoreCheckoutRoute: StoreCheckoutRoute,
  StoreIndexRoute: StoreIndexRoute,
}

const StoreRouteRouteWithChildren = StoreRouteRoute._addFileChildren(
  StoreRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  NewsRouteRoute: NewsRouteRouteWithChildren,
  ProductRouteRoute: ProductRouteRouteWithChildren,
  StoreRouteRoute: StoreRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  DeliveryRoute: DeliveryRoute,
  LoginRoute: LoginRoute,
  RedirectRoute: RedirectRoute,
  TunnelRoute: TunnelRoute,
  OrderOrderIdRoute: OrderOrderIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
